### ISSUE TITLE
P44 Solution?

### ISSUE THREAD

**Issue by tolly-xyz** [hyattj-osu/project-euler#1]
I had a sudden flash of insight about problem 44 as I was going to sleep last night and thought i would share.

We do not need to check for all pentagonal that add to another pentagonal and subtract to a pentagonal separately. For example, imagine we run the search for adding pentagonals, and a pair of such numbers is Pi and Pj. Pi + Pj = Pk, is known to also be pentagonal. 

This means that Pk - Pj = Pi. We can then check to see if Pk + Pj is pentagonal. Repeat for all Pi and Pj, then the minimum Pi is our answer.

Hopefully that makes sense! I’ll test it later and see if it works.

**Comment by hyattj-osu** [comment]
Good thoughts! That line of thinking did the trick. Commit 9eb46b8f74ad7dfc59ad5ba49b7af18e11baa2da is as far as I could think to take making it efficient. It finds an answer on my computer in just under 30 seconds.
